import { useMemo, useState } from "react";
import { worldDefinitions } from "../model/worldDefinitions";
import { WORLD_EXAMPLES } from "../model/worldExamples";
import { getSimulationAnalysisLabel } from "../model/simulationConfig";

export default function ComponentSidebar() {
  const [query, setQuery] = useState("");
  const definitions = useMemo(() => Object.entries(worldDefinitions).filter(([, definition]) => definition.type.toLowerCase().includes(query.toLowerCase())), [query]);
  const examples = useMemo(() => WORLD_EXAMPLES.filter((example) => `${example.label} ${example.description}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const dispatch = (name, detail) => window.dispatchEvent(new CustomEvent(name, { detail }));
  return <div data-testid="component-palette" className="flex h-full min-h-0 flex-col bg-[#fafbfc]"><header className="shrink-0 border-b border-[#d9dde2] bg-white px-4 py-3"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#58718f]">Library</div><div className="mt-0.5 text-sm font-semibold text-[#17253a]">Components</div><input aria-label="Search components" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search components" className="mt-3 h-8 w-full border border-[#cfd5dc] bg-white px-2.5 text-xs outline-none focus:border-[#58718f]"/></header><div className="min-h-0 flex-1 overflow-y-auto p-3">{examples.length>0&&<section className="mb-4"><div className="mb-2 text-[9px] font-semibold uppercase tracking-[0.12em] text-[#69717b]">Examples</div><div className="space-y-1">{examples.map((example)=><button key={example.id} type="button" onClick={()=>dispatch("worlds:load-example",example)} className="w-full border border-[#e1e5e9] bg-white px-2.5 py-2 text-left hover:border-[#9da8b5]"><div className="flex items-center justify-between gap-2"><span className="truncate text-[10px] font-semibold text-[#26364d]">{example.label}</span><span className="shrink-0 text-[8px] uppercase tracking-[0.08em] text-[#58718f]">{getSimulationAnalysisLabel(example.simulationPreset.analysis)}</span></div><div className="mt-0.5 line-clamp-2 text-[9px] leading-4 text-[#8a929c]">{example.description}</div></button>)}</div></section>}<section><div className="mb-2 text-[9px] font-semibold uppercase tracking-[0.12em] text-[#69717b]">Components</div><div className="grid grid-cols-1 gap-1">{definitions.map(([key,definition])=><button key={key} type="button" onClick={()=>dispatch("worlds:add-component",key)} className="flex items-center justify-between border border-[#e1e5e9] bg-white px-2.5 py-2 text-left hover:border-[#9da8b5]"><span className="text-[10px] font-medium text-[#26364d]">{definition.type}</span><span className="text-[8px] text-[#8a929c]">+</span></button>)}</div></section></div></div>;
}
