import { useMemo, useState } from "react";
import { worldDefinitions } from "../model/worldDefinitions";
import { WORLD_EXAMPLES } from "../model/worldExamples";
import { getSimulationAnalysisLabel } from "../model/simulationConfig";
import ComponentSymbolPreview from "./ComponentSymbolPreview";

const GROUPS = [["Basic", ["Resistor", "Capacitor", "Inductor"]], ["Sources", ["Voltage Source", "Current Source"]], ["References", ["Ground"]], ["Diodes", ["Diode"]], ["Transistors", ["NPN Transistor", "PNP Transistor"]], ["MOSFETs", ["NMOS", "PMOS"]]];
function emit(name, detail) { window.dispatchEvent(new CustomEvent(name, { detail })); }
function SectionLabel({ children, count }) { return <div className="mb-2 flex items-center justify-between"><div className="text-[9px] font-bold uppercase tracking-[0.16em] text-[#69788a]">{children}</div>{count !== undefined && <span className="rounded-full bg-[#edf1f5] px-1.5 py-0.5 text-[8px] font-semibold tabular-nums text-[#8a95a2]">{count}</span>}</div>; }

export default function ComponentLibrary() {
  const [query, setQuery] = useState("");
  const [recent, setRecent] = useState([]);
  const normalized = query.trim().toLowerCase();
  const definitions = useMemo(() => Object.entries(worldDefinitions).filter(([, definition]) => !normalized || `${definition.type} ${definition.description ?? ""}`.toLowerCase().includes(normalized)), [normalized]);
  const visibleExamples = WORLD_EXAMPLES.filter(example => !normalized || `${example.label} ${example.description}`.toLowerCase().includes(normalized));
  const recentDefinitions = recent.map(key => [key, worldDefinitions[key]]).filter(([, definition]) => definition && (!normalized || `${definition.type} ${definition.description ?? ""}`.toLowerCase().includes(normalized)));
  const chooseComponent = key => { setRecent(current => [key, ...current.filter(item => item !== key)].slice(0, 5)); emit("worlds:begin-placement", key); emit("worlds:close-library"); };
  return <div data-testid="component-library" className="flex h-full min-h-0 flex-col bg-[#f7f9fa]">
    <div className="shrink-0 border-b border-[#dce3e9] bg-[#f7f9fa] px-4 pb-3 pt-4"><div className="flex items-center justify-between"><div><div className="text-[8px] font-bold uppercase tracking-[0.2em] text-[#8a97a6]">Place</div><div className="mt-0.5 text-sm font-semibold tracking-[-0.015em] text-[#1e3047]">Component</div></div><button type="button" aria-label="Close component tool" onClick={() => emit("worlds:close-library")} className="flex h-7 w-7 items-center justify-center rounded-md text-[#8d99a6] hover:bg-[#e9eef2] hover:text-[#41556d]">×</button></div><div className="relative mt-3"><span className="pointer-events-none absolute left-2.5 top-1/2 -translate-y-1/2 text-[#9ba5b1]">⌕</span><input autoFocus aria-label="Search components" value={query} onChange={event => setQuery(event.target.value)} placeholder="Type to find a component" className="h-10 w-full rounded-lg border border-[#cfd8e0] bg-white pl-7 pr-3 text-[11px] text-[#26364d] outline-none transition placeholder:text-[#9ba5b4] focus:border-[#71869c] focus:ring-2 focus:ring-[#e4e9ee]" /></div><div className="mt-2 text-[8px] text-[#97a2ad]">Choose a symbol, then click where it belongs on the schematic.</div></div>
    <div className="min-h-0 flex-1 overflow-y-auto px-3 pb-4 pt-3">
      {!normalized && recentDefinitions.length > 0 && <section className="mb-4"><SectionLabel>Recently used</SectionLabel><div className="grid grid-cols-2 gap-1.5">{recentDefinitions.map(([key, definition]) => <button key={key} type="button" aria-label={`${definition.type} Add to canvas`} onClick={() => chooseComponent(key)} className="group flex min-h-[66px] flex-col items-center justify-center rounded-lg border border-[#d7dfe6] bg-white p-1.5 text-center transition hover:border-[#aebbc8] hover:shadow-sm"><ComponentSymbolPreview type={definition.type} className="h-8 w-16"/><span className="mt-1 truncate text-[9px] font-semibold text-[#405067]">{definition.type}</span></button>)}</div></section>}
      {!normalized && <section data-testid="world-examples" className="mb-4"><SectionLabel count={visibleExamples.length}>Start from an example</SectionLabel><div className="grid gap-1">{visibleExamples.map(example => <button key={example.id} type="button" onClick={() => emit("worlds:load-example", example)} className="group flex items-center gap-2 rounded-lg border border-transparent bg-white px-2.5 py-2 text-left transition hover:border-[#d6dfe6] hover:bg-white hover:shadow-sm"><span className="min-w-0 flex-1"><span className="block truncate text-[10px] font-semibold text-[#2d3d54]">{example.label}</span><span className="mt-0.5 block truncate text-[8px] text-[#919ca8]">{example.description}</span></span><span className="shrink-0 text-[7px] font-bold uppercase tracking-[0.06em] text-[#8391a0]">{getSimulationAnalysisLabel(example.simulationPreset.analysis)}</span></button>)}</div></section>}
      <section data-testid="component-palette"><SectionLabel count={definitions.length}>Symbols</SectionLabel>{GROUPS.map(([group, types]) => { const entries = definitions.filter(([, definition]) => types.includes(definition.type)); if (!entries.length) return null; return <div key={group} className="mb-4"><div className="mb-1.5 px-1 text-[8px] font-bold uppercase tracking-[0.14em] text-[#9aa3ad]">{group}</div><div className="grid grid-cols-2 gap-1.5">{entries.map(([key, definition]) => <button key={key} type="button" aria-label={`${definition.type} Add to canvas`} onClick={() => chooseComponent(key)} className="group flex min-h-[74px] flex-col items-center justify-center rounded-lg border border-[#d8e0e7] bg-white p-1.5 text-center transition hover:-translate-y-px hover:border-[#aebbc8] hover:shadow-[0_4px_12px_rgba(24,37,58,0.07)]"><ComponentSymbolPreview type={definition.type} className="h-9 w-16"/><span className="mt-1 truncate text-[9px] font-semibold text-[#405067]">{definition.type}</span></button>)}</div></div>; })}</section>
    </div>
  </div>;
}
