import { useEffect, useState } from "react";
import { worldDefinitions } from "../model/worldDefinitions";
import ComponentPropertiesPanel from "./ComponentPropertiesPanel";

function addProbe(node, measurement, terminal = null) {
  if (!node) return;
  window.dispatchEvent(new CustomEvent("worlds:add-probe", { detail: { entityType: terminal ? "terminal" : "component", entityId: terminal ? `${node.id}:${terminal.id}` : node.id, nodeId: node.id, terminalId: terminal?.id ?? null, measurement, label: terminal ? `${node.data?.label ?? "Component"} · ${terminal.label ?? terminal.id}` : node.data?.label ?? "Component" } }));
}

function ProbeButton({ label, onClick, disabled = false }) {
  return <button type="button" disabled={disabled} onClick={onClick} className="border border-[#cfd5dc] bg-white px-2 py-1.5 text-[9px] font-medium text-[#35445a] hover:bg-[#f5f7f9] disabled:cursor-not-allowed disabled:opacity-40">{label}</button>;
}

function ProbeRow({ label, measurement, onRemove }) {
  return <div className="flex items-center justify-between gap-2 border-b border-[#eef0f3] py-2 last:border-b-0"><div className="min-w-0"><div className="truncate text-[10px] font-medium text-[#26364d]">{label}</div><div className="text-[8px] uppercase tracking-[0.08em] text-[#8a929c]">{measurement}</div></div><button type="button" aria-label={`Remove ${label} ${measurement} probe`} onClick={onRemove} className="shrink-0 px-1 text-sm leading-none text-[#8a929c] hover:text-[#26364d]">×</button></div>;
}

export default function WorkspaceInspector() {
  const [selection, setSelection] = useState({ selectedNode: null, selectedEdgeId: null, selectedTerminal: null, selectedResultEntity: null });
  const [probes, setProbes] = useState([]);
  useEffect(() => { const handler=event=>setSelection(event.detail??{}); window.addEventListener("worlds:selection-change", handler); return()=>window.removeEventListener("worlds:selection-change", handler); }, []);
  useEffect(() => { const handler=event=>{ const probe=event.detail; if(!probe?.entityId||!probe?.measurement)return; setProbes(current=>current.some(item=>item.entityId===probe.entityId&&item.measurement===probe.measurement)?current:[...current,probe]); }; const removeHandler=event=>{const probe=event.detail;if(!probe?.entityId||!probe?.measurement)return;setProbes(current=>current.filter(item=>!(item.entityId===probe.entityId&&item.measurement===probe.measurement)));}; window.addEventListener("worlds:add-probe",handler); window.addEventListener("worlds:remove-probe",removeHandler); return()=>{window.removeEventListener("worlds:add-probe",handler);window.removeEventListener("worlds:remove-probe",removeHandler);}; }, []);
  const node=selection.selectedNode;
  const definition=node?.data?.definitionKey?worldDefinitions[node.data.definitionKey]:null;
  const terminal=selection.selectedTerminal?.port;
  const update=(property,value)=>window.dispatchEvent(new CustomEvent("worlds:update-property", { detail:{ nodeId:node?.id, property, value } }));
  const removeProbe=(entityId,measurement)=>window.dispatchEvent(new CustomEvent("worlds:remove-probe", { detail:{ entityId, measurement } }));
  const clearSelection=()=>window.dispatchEvent(new CustomEvent("worlds:selection-change", { detail:{ selectedNode:null, selectedEdgeId:null, selectedTerminal:null, selectedResultEntity:null } }));
  if(terminal&&node)return <div data-testid="workspace-inspector" className="flex h-full min-h-0 flex-col overflow-y-auto"><div className="border-b border-[#e3e6ea] px-3 py-3"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#667382]">Terminal</div><div className="mt-1 text-base font-semibold text-[#17253a]">{terminal.label??terminal.id}</div><div className="mt-0.5 text-[9px] font-semibold uppercase tracking-[0.1em] text-[#58718f]">{node.data?.label??"Component"}</div></div><div className="px-3 py-4"><div className="grid grid-cols-[70px_1fr] gap-y-2 text-[10px]"><span className="text-[#8a929c]">Port</span><span className="font-mono text-[#26364d]">{terminal.id}</span><span className="text-[#8a929c]">Kind</span><span className="text-[#26364d]">{terminal.kind}</span><span className="text-[#8a929c]">Position</span><span className="text-[#26364d]">{terminal.position}</span></div></div><div className="border-t border-[#e3e6ea] px-3 py-3"><div className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#69717b]">Probe</div><div className="mt-2 flex flex-wrap gap-1.5"><ProbeButton label="Voltage" onClick={()=>addProbe(node,"voltage",terminal)}/><ProbeButton label="Current" disabled={terminal.kind !== "electrical"} onClick={()=>addProbe(node,"current",terminal)}/><ProbeButton label="Power" disabled={terminal.kind !== "electrical"} onClick={()=>addProbe(node,"power",terminal)}/></div></div><div className="border-t border-[#e3e6ea] px-3 py-3 text-xs leading-5 text-[#69717b]">Probe a terminal to add its quantity to the Instrument panel.</div><div className="mt-auto border-t border-[#e3e6ea] px-3 py-2"><button type="button" onClick={clearSelection} className="text-[9px] font-medium text-[#69717b] hover:text-[#26364d]">Clear selection</button></div></div>;
  if(selection.selectedResultEntity&&!node)return <div data-testid="workspace-inspector" className="flex h-full flex-col"><div className="border-b border-[#e3e6ea] px-3 py-3"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#667382]">Result selection</div><div className="mt-1 text-sm font-semibold text-[#26364d]">{selection.selectedResultEntity.label??selection.selectedResultEntity.entityId}</div></div><div className="px-3 py-4 text-xs leading-5 text-[#69717b]">This result is linked to the corresponding circuit quantity. Use the Instrument panel for waveform and measurement details.</div></div>;
  if(selection.selectedEdgeId)return <div data-testid="workspace-inspector" className="flex h-full flex-col"><div className="border-b border-[#e3e6ea] px-3 py-3"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#69717b]">Wire / net</div><div className="mt-1 font-mono text-xs text-[#26364d]">{selection.selectedEdgeId}</div></div><div className="px-3 py-4 text-xs leading-5 text-[#69717b]">Connection topology is defined by the circuit graph. Select a component or result to inspect its properties.</div></div>;
  if(!node)return <div data-testid="workspace-inspector" className="flex h-full min-h-0 flex-col"><div className="flex flex-1 items-center justify-center px-5 text-center text-xs leading-5 text-[#8a929c]">Select a component, terminal, wire, or result to inspect it.</div>{probes.length>0&&<div className="shrink-0 border-t border-[#e3e6ea] px-3 py-3"><div className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#69717b]">Active probes</div>{probes.map(probe=><ProbeRow key={`${probe.entityId}:${probe.measurement}`} label={probe.label} measurement={probe.measurement} onRemove={()=>removeProbe(probe.entityId,probe.measurement)}/>)}</div>}</div>;
  return <div data-testid="workspace-inspector" className="flex h-full min-h-0 flex-col overflow-y-auto"><div className="border-b border-[#e3e6ea] px-3 py-3"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#667382]">Component</div><div className="mt-1 text-base font-semibold text-[#17253a]">{node.data?.label??"Unnamed"}</div><div className="mt-0.5 text-[9px] font-semibold uppercase tracking-[0.1em] text-[#58718f]">{node.data?.componentType??"Component"}</div></div><div className="px-3"><ComponentPropertiesPanel definition={definition} properties={node.data?.properties??{}} onChange={update}/></div><div className="border-t border-[#e3e6ea] px-3 py-3"><div className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#69717b]">Probe</div><div className="mt-2 flex flex-wrap gap-1.5"><ProbeButton label="Voltage" onClick={()=>addProbe(node,"voltage")}/><ProbeButton label="Current" onClick={()=>addProbe(node,"current")}/><ProbeButton label="Power" onClick={()=>addProbe(node,"power")}/></div><div className="mt-2 text-[9px] leading-4 text-[#8a929c]">Add a quantity to the Instrument panel for analysis and measurement.</div></div><div className="border-t border-[#e3e6ea] px-3 py-3"><div className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#69717b]">Ports</div><div className="mt-2 space-y-1">{(node.data?.ports??[]).map(port=><div key={port.id} className="flex items-center justify-between text-[10px]"><span>{port.label??port.id}</span><span className="text-[#8a929c]">{port.kind}</span></div>)}</div></div>{probes.length>0&&<div className="border-t border-[#e3e6ea] px-3 py-3"><div className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#69717b]">Active probes</div>{probes.map(probe=><ProbeRow key={`${probe.entityId}:${probe.measurement}`} label={probe.label} measurement={probe.measurement} onRemove={()=>removeProbe(probe.entityId,probe.measurement)}/>)}</div>}</div>;
}
