import { useEffect, useState } from "react";
import { worldDefinitions } from "../model/worldDefinitions";
import ComponentPropertiesPanel from "./ComponentPropertiesPanel";

function addProbe(node, measurement, terminal = null) {
  if (!node) return;
  window.dispatchEvent(new CustomEvent("worlds:add-probe", { detail: { entityType: terminal ? "terminal" : "component", entityId: terminal ? `${node.id}:${terminal.id}` : node.id, nodeId: node.id, terminalId: terminal?.id ?? null, measurement, label: terminal ? `${node.data?.label ?? "Component"} · ${terminal.label ?? terminal.id}` : node.data?.label ?? "Component" } }));
}

function ProbeButton({ label, onClick, disabled = false }) {
  return <button type="button" disabled={disabled} onClick={onClick} className="border border-[#cfd5dc] bg-white px-2 py-1.5 text-[9px] font-medium text-[#35445a] hover:bg-[#f5f7f9] disabled:cursor-not-allowed disabled:opacity-40">{label}</button>;
}

export default function WorkspaceInspector() {
  const [selection, setSelection] = useState({ selectedNode: null, selectedEdgeId: null, selectedTerminal: null, selectedResultEntity: null });
  useEffect(() => { const handler=event=>setSelection(event.detail??{}); window.addEventListener("worlds:selection-change", handler); return()=>window.removeEventListener("worlds:selection-change", handler); }, []);
  const node=selection.selectedNode;
  const definition=node?.data?.definitionKey?worldDefinitions[node.data.definitionKey]:null;
  const terminal=selection.selectedTerminal?.port;
  const update=(property,value)=>window.dispatchEvent(new CustomEvent("worlds:update-property", { detail:{ nodeId:node?.id, property, value } }));
  if(terminal&&node)return <div data-testid="workspace-inspector" className="flex h-full min-h-0 flex-col overflow-y-auto"><div className="border-b border-[#e3e6ea] px-3 py-3"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#667382]">Terminal</div><div className="mt-1 text-base font-semibold text-[#17253a]">{terminal.label??terminal.id}</div><div className="mt-0.5 text-[9px] font-semibold uppercase tracking-[0.1em] text-[#58718f]">{node.data?.label??"Component"}</div></div><div className="px-3 py-4"><div className="grid grid-cols-[70px_1fr] gap-y-2 text-[10px]"><span className="text-[#8a929c]">Port</span><span className="font-mono text-[#26364d]">{terminal.id}</span><span className="text-[#8a929c]">Kind</span><span className="text-[#26364d]">{terminal.kind}</span><span className="text-[#8a929c]">Position</span><span className="text-[#26364d]">{terminal.position}</span></div></div><div className="border-t border-[#e3e6ea] px-3 py-3"><div className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#69717b]">Probe</div><div className="mt-2 flex gap-1.5"><ProbeButton label="Voltage" onClick={()=>addProbe(node,"voltage",terminal)}/><ProbeButton label="Current" disabled={terminal.kind !== "electrical"} onClick={()=>addProbe(node,"current",terminal)}/></div></div><div className="border-t border-[#e3e6ea] px-3 py-3 text-xs leading-5 text-[#69717b]">This terminal is part of the component connection topology. Add a quantity to the Instrument panel to inspect it.</div></div>;
  if(selection.selectedResultEntity&&!node)return <div data-testid="workspace-inspector" className="flex h-full flex-col"><div className="border-b border-[#e3e6ea] px-3 py-3"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#667382]">Result selection</div><div className="mt-1 text-sm font-semibold text-[#26364d]">{selection.selectedResultEntity.label??selection.selectedResultEntity.entityId}</div></div><div className="px-3 py-4 text-xs leading-5 text-[#69717b]">This result is linked to the corresponding circuit quantity. Use the Instrument panel for waveform and measurement details.</div></div>;
  if(selection.selectedEdgeId)return <div data-testid="workspace-inspector" className="flex h-full flex-col"><div className="border-b border-[#e3e6ea] px-3 py-3"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#667382]">Wire / net</div><div className="mt-1 font-mono text-xs text-[#26364d]">{selection.selectedEdgeId}</div></div><div className="px-3 py-4 text-xs leading-5 text-[#69717b]">Connection topology is defined by the circuit graph. Select a component or result to inspect its properties.</div></div>;
  if(!node)return <div data-testid="workspace-inspector" className="flex flex-1 items-center justify-center px-5 text-center text-xs leading-5 text-[#8a929c]">Select a component, terminal, wire, or result to inspect it.</div>;
  return <div data-testid="workspace-inspector" className="flex h-full min-h-0 flex-col overflow-y-auto"><div className="border-b border-[#e3e6ea] px-3 py-3"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#667382]">Component</div><div className="mt-1 text-base font-semibold text-[#17253a]">{node.data?.label??"Unnamed"}</div><div className="mt-0.5 text-[9px] font-semibold uppercase tracking-[0.1em] text-[#58718f]">{node.data?.componentType??"Component"}</div></div><div className="px-3"><ComponentPropertiesPanel definition={definition} properties={node.data?.properties??{}} onChange={update}/></div><div className="border-t border-[#e3e6ea] px-3 py-3"><div className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#69717b]">Probe</div><div className="mt-2 flex gap-1.5"><ProbeButton label="Voltage" onClick={()=>addProbe(node,"voltage")}/><ProbeButton label="Current" onClick={()=>addProbe(node,"current")}/></div><div className="mt-2 text-[9px] leading-4 text-[#8a929c]">Add a quantity to the Instrument panel for analysis and measurement.</div></div><div className="border-t border-[#e3e6ea] px-3 py-3"><div className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#69717b]">Ports</div><div className="mt-2 space-y-1">{(node.data?.ports??[]).map(port=><div key={port.id} className={`flex items-center justify-between text-[10px] ${terminal?.id===port.id?"font-semibold text-[#26364d]":""}`}><span>{port.label??port.id}</span><span className="text-[#8a929c]">{port.kind}</span></div>)}</div></div></div>;
}
