import { useEffect, useState } from "react";
import { worldDefinitions } from "../model/worldDefinitions";
import ComponentPropertiesPanel from "./ComponentPropertiesPanel";

export default function WorkspaceInspector() {
  const [selection, setSelection] = useState({ selectedNode: null, selectedEdgeId: null, selectedResultEntity: null });
  useEffect(() => { const handler=event=>setSelection(event.detail??{}); window.addEventListener("worlds:selection-change", handler); return()=>window.removeEventListener("worlds:selection-change", handler); }, []);
  const node=selection.selectedNode;
  const definition=node?.data?.definitionKey?worldDefinitions[node.data.definitionKey]:null;
  const update=(property,value)=>window.dispatchEvent(new CustomEvent("worlds:update-property", { detail:{ nodeId:node?.id, property, value } }));
  if(selection.selectedResultEntity&&!node)return <div data-testid="workspace-inspector" className="flex h-full flex-col"><div className="border-b border-[#e3e6ea] px-3 py-3"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#667382]">Result selection</div><div className="mt-1 text-sm font-semibold text-[#26364d]">{selection.selectedResultEntity.label??selection.selectedResultEntity.entityId}</div></div><div className="px-3 py-4 text-xs leading-5 text-[#69717b]">This result is linked to the corresponding circuit quantity. Use the Instrument panel for waveform and measurement details.</div></div>;
  if(selection.selectedEdgeId)return <div data-testid="workspace-inspector" className="flex h-full flex-col"><div className="border-b border-[#e3e6ea] px-3 py-3"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#667382]">Wire / net</div><div className="mt-1 font-mono text-xs text-[#26364d]">{selection.selectedEdgeId}</div></div><div className="px-3 py-4 text-xs leading-5 text-[#69717b]">Connection topology is defined by the circuit graph. Select a component or result to inspect its properties.</div></div>;
  if(!node)return <div data-testid="workspace-inspector" className="flex flex-1 items-center justify-center px-5 text-center text-xs leading-5 text-[#8a929c]">Select a component, terminal, wire, or result to inspect it.</div>;
  return <div data-testid="workspace-inspector" className="flex h-full min-h-0 flex-col overflow-y-auto"><div className="border-b border-[#e3e6ea] px-3 py-3"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#667382]">Component</div><div className="mt-1 text-base font-semibold text-[#17253a]">{node.data?.label??"Unnamed"}</div><div className="mt-0.5 text-[9px] font-semibold uppercase tracking-[0.1em] text-[#58718f]">{node.data?.componentType??"Component"}</div></div><div className="px-3"><ComponentPropertiesPanel definition={definition} properties={node.data?.properties??{}} onChange={update}/></div><div className="border-t border-[#e3e6ea] px-3 py-3"><div className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#69717b]">Ports</div><div className="mt-2 space-y-1">{(node.data?.ports??[]).map(port=><div key={port.id} className="flex items-center justify-between text-[10px]"><span className="text-[#26364d]">{port.label??port.id}</span><span className="text-[#8a929c]">{port.kind}</span></div>)}</div></div></div>;
}
