from __future__ import annotations

from dataclasses import dataclass, field, replace
from decimal import Decimal, InvalidOperation
from typing import Mapping, Protocol

from worlds.math import Variable

from .model import SimulationModel
from .network import build_network_equation_system
from .solver import BranchCurrent, SimulationResult, SimulationSolver


DC_OPERATING_POINT = "dc_operating_point"
DC_SWEEP = "dc_sweep"
SUPPORTED_ANALYSES = (DC_OPERATING_POINT, DC_SWEEP)

MAX_SWEEP_POINTS = 10_000


class SimulationAnalysisError(ValueError):
    """Raised when a simulation analysis configuration is invalid."""


@dataclass(frozen=True)
class SimulationConfiguration:
    """Validated configuration describing one simulation run."""

    analysis: str = DC_OPERATING_POINT
    settings: Mapping[str, object] = field(default_factory=dict)
    outputs: tuple[str, ...] = ()

    @classmethod
    def from_dict(cls, value: Mapping[str, object] | None) -> "SimulationConfiguration":
        if value is None:
            return cls()
        if not isinstance(value, Mapping):
            raise SimulationAnalysisError("simulation must be an object")

        analysis = value.get("analysis", DC_OPERATING_POINT)
        if not isinstance(analysis, str) or not analysis:
            raise SimulationAnalysisError("simulation.analysis must be a non-empty string")
        if analysis not in SUPPORTED_ANALYSES:
            supported = ", ".join(SUPPORTED_ANALYSES)
            raise SimulationAnalysisError(
                f"Unsupported simulation analysis '{analysis}'. Supported analyses: {supported}"
            )

        settings = value.get("settings", {})
        if settings is None:
            settings = {}
        if not isinstance(settings, Mapping):
            raise SimulationAnalysisError("simulation.settings must be an object")

        outputs = value.get("outputs", [])
        if outputs is None:
            outputs = []
        if not isinstance(outputs, list) or not all(isinstance(item, str) for item in outputs):
            raise SimulationAnalysisError("simulation.outputs must be a list of strings")

        if analysis == DC_SWEEP:
            cls._validate_dc_sweep_settings(settings)

        return cls(
            analysis=analysis,
            settings=dict(settings),
            outputs=tuple(outputs),
        )

    @staticmethod
    def _validate_dc_sweep_settings(settings: Mapping[str, object]) -> None:
        source_id = settings.get("source")
        if not isinstance(source_id, str) or not source_id:
            raise SimulationAnalysisError("dc_sweep.settings.source must be a non-empty string")

        parameter = settings.get("parameter")
        if parameter is not None and (not isinstance(parameter, str) or not parameter):
            raise SimulationAnalysisError("dc_sweep.settings.parameter must be a non-empty string")

        for name in ("start", "stop", "step"):
            _parse_finite_decimal(settings.get(name), name)

        step = _parse_finite_decimal(settings.get("step"), "step")
        if step == 0:
            raise SimulationAnalysisError("dc_sweep.settings.step must not be zero")

        start = _parse_finite_decimal(settings.get("start"), "start")
        stop = _parse_finite_decimal(settings.get("stop"), "stop")
        if start < stop and step < 0:
            raise SimulationAnalysisError("dc_sweep.settings.step must be positive when start is below stop")
        if start > stop and step > 0:
            raise SimulationAnalysisError("dc_sweep.settings.step must be negative when start is above stop")

        if _count_sweep_points(start, stop, step) > MAX_SWEEP_POINTS:
            raise SimulationAnalysisError(f"dc_sweep produces more than {MAX_SWEEP_POINTS} points")

    def to_dict(self) -> dict[str, object]:
        return {
            "analysis": self.analysis,
            "settings": dict(self.settings),
            "outputs": list(self.outputs),
        }


@dataclass(frozen=True)
class DCSweepResult:
    """Collection of DC operating-point results generated by one sweep."""

    source_id: str
    parameter: str
    points: tuple[Decimal, ...]
    results: tuple[SimulationResult, ...]


class SimulationAnalysis(Protocol):
    key: str

    def run(
        self,
        model: SimulationModel,
        *,
        known: dict[object, float] | None = None,
        configuration: SimulationConfiguration | None = None,
    ) -> object:
        ...


class DCOperatingPointAnalysis:
    key = DC_OPERATING_POINT

    def run(
        self,
        model: SimulationModel,
        *,
        known: dict[object, float] | None = None,
        configuration: SimulationConfiguration | None = None,
    ) -> SimulationResult:
        equation_system = build_network_equation_system(model)
        solved = SimulationSolver().solve(equation_system, known=known)
        return SimulationResult(
            values=solved.values,
            instances={component.name: component for component in model.components},
        )


class DCSweepAnalysis:
    key = DC_SWEEP

    def run(
        self,
        model: SimulationModel,
        *,
        known: dict[object, float] | None = None,
        configuration: SimulationConfiguration | None = None,
    ) -> DCSweepResult:
        if configuration is None:
            raise SimulationAnalysisError("dc_sweep requires a simulation configuration")

        source_id, parameter, start, stop, step = self._parse_settings(configuration.settings, model)
        points = _build_sweep_points(start, stop, step)
        base_known = dict(known or {})
        results = []

        for point in points:
            swept_model = _override_component_parameter(
                model,
                source_id=source_id,
                parameter=parameter,
                value=float(point),
            )
            equation_system = build_network_equation_system(swept_model)
            solved = SimulationSolver().solve(equation_system, known=base_known)
            results.append(
                SimulationResult(
                    values=solved.values,
                    instances={component.name: component for component in swept_model.components},
                )
            )

        return DCSweepResult(
            source_id=source_id,
            parameter=parameter,
            points=tuple(points),
            results=tuple(results),
        )

    @staticmethod
    def _parse_settings(settings: Mapping[str, object], model: SimulationModel):
        source_id = settings.get("source")
        if not isinstance(source_id, str) or not source_id:
            raise SimulationAnalysisError("dc_sweep.settings.source must be a non-empty string")

        matches = [component for component in model.components if component.component_id == source_id]
        if not matches:
            raise SimulationAnalysisError(f"dc_sweep source '{source_id}' does not exist in the circuit")
        if len(matches) > 1:
            raise SimulationAnalysisError(f"dc_sweep source '{source_id}' is not unique")

        source = matches[0]
        parameter = settings.get("parameter")
        if parameter is None:
            parameter = {"VoltageSource": "V", "CurrentSource": "I"}.get(source.component_type)
            if parameter is None and len(source.parameters) == 1:
                parameter = next(iter(source.parameters))
        if not isinstance(parameter, str) or not parameter:
            raise SimulationAnalysisError(
                f"dc_sweep target '{source_id}' requires an explicit parameter"
            )
        if parameter not in source.parameters:
            available = ", ".join(sorted(source.parameters)) or "none"
            raise SimulationAnalysisError(
                f"dc_sweep target '{source_id}' does not expose parameter '{parameter}' (available: {available})"
            )

        start = _parse_finite_decimal(settings.get("start"), "start")
        stop = _parse_finite_decimal(settings.get("stop"), "stop")
        step = _parse_finite_decimal(settings.get("step"), "step")

        if step == 0:
            raise SimulationAnalysisError("dc_sweep.settings.step must not be zero")
        if start < stop and step < 0:
            raise SimulationAnalysisError("dc_sweep.settings.step must be positive when start is below stop")
        if start > stop and step > 0:
            raise SimulationAnalysisError("dc_sweep.settings.step must be negative when start is above stop")

        if _count_sweep_points(start, stop, step) > MAX_SWEEP_POINTS:
            raise SimulationAnalysisError(f"dc_sweep produces more than {MAX_SWEEP_POINTS} points")

        return source_id, parameter, start, stop, step


_ANALYSES: dict[str, SimulationAnalysis] = {
    DC_OPERATING_POINT: DCOperatingPointAnalysis(),
    DC_SWEEP: DCSweepAnalysis(),
}


def get_simulation_analysis(analysis: str) -> SimulationAnalysis:
    try:
        return _ANALYSES[analysis]
    except KeyError as exc:
        supported = ", ".join(SUPPORTED_ANALYSES)
        raise SimulationAnalysisError(
            f"Unsupported simulation analysis '{analysis}'. Supported analyses: {supported}"
        ) from exc


def _parse_finite_decimal(value: object, name: str) -> Decimal:
    if isinstance(value, bool) or value is None:
        raise SimulationAnalysisError(f"dc_sweep.settings.{name} must be a finite number")
    try:
        decimal = Decimal(str(value))
    except (InvalidOperation, ValueError):
        raise SimulationAnalysisError(f"dc_sweep.settings.{name} must be a finite number")
    if not decimal.is_finite():
        raise SimulationAnalysisError(f"dc_sweep.settings.{name} must be a finite number")
    return decimal


def _count_sweep_points(start: Decimal, stop: Decimal, step: Decimal) -> int:
    span = stop - start
    count = abs(span / step).to_integral_value(rounding="ROUND_FLOOR") + 1
    return int(count)


def _build_sweep_points(start: Decimal, stop: Decimal, step: Decimal) -> list[Decimal]:
    points: list[Decimal] = []
    value = start
    ascending = step > 0

    while (value <= stop if ascending else value >= stop):
        points.append(value)
        if len(points) > MAX_SWEEP_POINTS:
            raise SimulationAnalysisError(f"dc_sweep produces more than {MAX_SWEEP_POINTS} points")
        value += step

    return points


def _override_component_parameter(
    model: SimulationModel,
    *,
    source_id: str,
    parameter: str,
    value: float,
) -> SimulationModel:
    components = []
    found = False

    for component in model.components:
        if component.component_id != source_id:
            components.append(component)
            continue

        parameters = dict(component.parameters)
        parameters[parameter] = value
        components.append(replace(component, parameters=parameters))
        found = True

    if not found:
        raise SimulationAnalysisError(f"dc_sweep target '{source_id}' does not exist in the circuit")

    return SimulationModel(components=components, nodes=set(model.nodes))
