import test from "node:test";
import assert from "node:assert/strict";
import { WORLD_EXAMPLES } from "./worldExamples.js";
import { validateWorldGraphSchema } from "./worldGraphSchema.js";
import { buildCircuitDescription } from "./worldGraphSerializer.js";

test("electrical examples expose stable, complete graphs", () => {
  assert.deepEqual(WORLD_EXAMPLES.map((example) => example.id), ["voltage-divider", "rc-low-pass", "parallel-resistors", "rl-transient", "rlc-transient", "diode-rectifier", "npn-bias", "npn-low-side-switch", "pnp-high-side-switch", "nmos-low-side-switch", "pmos-high-side-switch", "cmos-inverter"]);
  for (const example of WORLD_EXAMPLES) { const graph=example.createGraph(); assert.deepEqual(validateWorldGraphSchema(graph.nodes,graph.edges),true); assert.ok(graph.nodes.length>0); assert.ok(graph.edges.length>0); assert.equal(graph.nodes.filter((node)=>node.data?.componentType==="Ground").length,1); assert.doesNotThrow(()=>buildCircuitDescription(graph.nodes,graph.edges)); }
});

test("electrical examples create independent graph instances",()=>{const first=WORLD_EXAMPLES[0].createGraph(),second=WORLD_EXAMPLES[0].createGraph();first.nodes[0].position.x=9999;first.nodes[0].data.properties.voltage=1;assert.equal(second.nodes[0].position.x,80);assert.equal(second.nodes[0].data.properties.voltage,10);});

test("electrical examples expose an explicit simulation preset",()=>{assert.deepEqual(WORLD_EXAMPLES.map((example)=>({id:example.id,...example.simulationPreset})),[
{id:"voltage-divider",analysis:"dc_operating_point",settings:{}},{id:"rc-low-pass",analysis:"transient",settings:{start:0,stop:0.005,step:0.00001}},{id:"parallel-resistors",analysis:"dc_operating_point",settings:{}},{id:"rl-transient",analysis:"transient",settings:{start:0,stop:0.00005,step:0.0000001}},{id:"rlc-transient",analysis:"transient",settings:{start:0,stop:0.005,step:0.000005}},{id:"diode-rectifier",analysis:"dc_operating_point",settings:{}},{id:"npn-bias",analysis:"dc_operating_point",settings:{}},{id:"npn-low-side-switch",analysis:"transient",settings:{start:0,stop:0.002,step:0.000001}},{id:"pnp-high-side-switch",analysis:"transient",settings:{start:0,stop:0.002,step:0.000001}},{id:"nmos-low-side-switch",analysis:"transient",settings:{start:0,stop:0.002,step:0.000001}},{id:"pmos-high-side-switch",analysis:"transient",settings:{start:0,stop:0.002,step:0.000001}},{id:"cmos-inverter",analysis:"transient",settings:{start:0,stop:0.002,step:0.000001}}]);for(const example of WORLD_EXAMPLES){assert.ok(Object.isFrozen(example.simulationPreset));assert.ok(Object.isFrozen(example.simulationPreset.settings));}});

test("PNP transistor example exposes three terminals and maps its parameters",()=>{const example=WORLD_EXAMPLES.find((candidate)=>candidate.id==="pnp-high-side-switch");assert.ok(example);const graph=example.createGraph();const transistor=graph.nodes.find((node)=>node.id==="Q1");assert.ok(transistor);assert.deepEqual(transistor.data.properties,{vbeOn:0.7,vceSat:0.2,beta:100});assert.deepEqual(transistor.data.ports.map((port)=>port.id),["b","c","e"]);const description=buildCircuitDescription(graph.nodes,graph.edges);const instance=description.instances.find((item)=>item.id==="Q1");assert.equal(instance.type,"PNPTransistor");assert.deepEqual(instance.parameters,{Vbe:0.7,VceSat:0.2,Beta:100});assert.equal(instance.ports.e!=="ground",true);});

test("PNP high-side switch example exposes correct control and load topology",()=>{const example=WORLD_EXAMPLES.find((candidate)=>candidate.id==="pnp-high-side-switch");assert.ok(example);const graph=example.createGraph();const source=graph.nodes.find((node)=>node.id==="VIN"),load=graph.nodes.find((node)=>node.id==="RLOAD");assert.deepEqual(source.data.properties,{waveform:"square",amplitude:6,offset:6,frequency:1000,phase:0,delay:0});assert.equal(load.data.properties.resistance,1000);assert.equal(graph.edges.some((edge)=>edge.source==="VCC"&&edge.target==="Q1"&&edge.targetHandle==="e"),true);assert.equal(graph.edges.some((edge)=>edge.source==="Q1"&&edge.target==="RLOAD"&&edge.sourceHandle==="c"),true);assert.equal(graph.edges.some((edge)=>edge.source==="RB"&&edge.target==="Q1"&&edge.targetHandle==="b"),true);});

test("MOSFET examples expose G/D/S terminals and switch parameters",()=>{for(const id of ["nmos-low-side-switch","pmos-high-side-switch"]){const example=WORLD_EXAMPLES.find((candidate)=>candidate.id===id);assert.ok(example);const graph=example.createGraph();const mosfet=graph.nodes.find((node)=>node.id==="Q1");assert.ok(mosfet);assert.deepEqual(mosfet.data.ports.map((port)=>port.id),["g","d","s"]);assert.deepEqual(mosfet.data.properties,{thresholdVoltage:1,onResistance:10});const instance=buildCircuitDescription(graph.nodes,graph.edges).instances.find((item)=>item.id==="Q1");assert.equal(instance.type,id.startsWith("nmos")?"NMOS":"PMOS");assert.deepEqual(instance.parameters,{Vth:1,RdsOn:10});}});

test("CMOS inverter ties complementary gates together and drains to one output",()=>{const example=WORLD_EXAMPLES.find((candidate)=>candidate.id==="cmos-inverter");assert.ok(example);const graph=example.createGraph();assert.equal(graph.nodes.filter((node)=>node.data?.componentType==="NMOS").length,1);assert.equal(graph.nodes.filter((node)=>node.data?.componentType==="PMOS").length,1);assert.equal(graph.edges.some((edge)=>edge.source==="VIN"&&edge.target==="Qp"&&edge.targetHandle==="g"),true);assert.equal(graph.edges.some((edge)=>edge.source==="VIN"&&edge.target==="Qn"&&edge.targetHandle==="g"),true);assert.equal(graph.edges.some((edge)=>edge.source==="Qp"&&edge.target==="Qn"&&edge.sourceHandle==="d"&&edge.targetHandle==="d"),true);});
