function makeNode(id, definitionKey, label, properties, x, y) {
  const portsByDefinition = {
    voltageSource: [{ id: "n", kind: "electrical", position: "left", label: "n" }, { id: "p", kind: "electrical", position: "right", label: "p" }],
    currentSource: [{ id: "p", kind: "electrical", position: "left", label: "p" }, { id: "n", kind: "electrical", position: "right", label: "n" }],
    resistor: [{ id: "p", kind: "electrical", position: "left", label: "p" }, { id: "n", kind: "electrical", position: "right", label: "n" }],
    diode: [{ id: "p", kind: "electrical", position: "left", label: "p" }, { id: "n", kind: "electrical", position: "right", label: "n" }],
    npnTransistor: [{ id: "b", kind: "electrical", position: "left", label: "B" }, { id: "c", kind: "electrical", position: "top", label: "C" }, { id: "e", kind: "electrical", position: "bottom", label: "E" }],
    pnpTransistor: [{ id: "b", kind: "electrical", position: "left", label: "B" }, { id: "c", kind: "electrical", position: "top", label: "C" }, { id: "e", kind: "electrical", position: "bottom", label: "E" }],
    capacitor: [{ id: "p", kind: "electrical", position: "left", label: "p" }, { id: "n", kind: "electrical", position: "right", label: "n" }],
    inductor: [{ id: "p", kind: "electrical", position: "left", label: "p" }, { id: "n", kind: "electrical", position: "right", label: "n" }],
    ground: [{ id: "g", kind: "electrical", position: "top", label: "GND" }],
  };
  const componentTypes = { voltageSource: "Voltage Source", currentSource: "Current Source", resistor: "Resistor", diode: "Diode", npnTransistor: "NPN Transistor", pnpTransistor: "PNP Transistor", capacitor: "Capacitor", inductor: "Inductor", ground: "Ground" };
  return { id, type: "world", position: { x, y }, data: { label, description: componentTypes[definitionKey], componentType: componentTypes[definitionKey], ports: portsByDefinition[definitionKey], definitionKey, properties } };
}
function makeEdge(id, source, sourceHandle, target, targetHandle) { return { id, source, sourceHandle, target, targetHandle, type: "circuit" }; }
function simulationPreset(analysis, settings = {}) { return Object.freeze({ analysis, settings: Object.freeze({ ...settings }) }); }

export const WORLD_EXAMPLES = Object.freeze([
  Object.freeze({ id: "voltage-divider", label: "Voltage divider", description: "10 V source with two resistors in series.", simulationPreset: simulationPreset("dc_operating_point"), createGraph: () => ({ nodes: [makeNode("V1", "voltageSource", "Voltage Source 1", { waveform: "dc", voltage: 10 }, 80, 120), makeNode("R1", "resistor", "Resistor 1", { resistance: 1000 }, 300, 80), makeNode("R2", "resistor", "Resistor 2", { resistance: 1000 }, 300, 220), makeNode("GND1", "ground", "Ground 1", {}, 520, 150)], edges: [makeEdge("e1", "V1", "p", "R1", "p"), makeEdge("e2", "R1", "n", "R2", "p"), makeEdge("e3", "R2", "n", "GND1", "g"), makeEdge("e4", "V1", "n", "GND1", "g")] }) }),
  Object.freeze({ id: "rc-low-pass", label: "RC low-pass", description: "Sine source driving a resistor-capacitor network.", simulationPreset: simulationPreset("transient", { start: 0, stop: 0.005, step: 0.00001 }), createGraph: () => ({ nodes: [makeNode("V1", "voltageSource", "Voltage Source 1", { waveform: "sine", amplitude: 5, offset: 0, frequency: 1000, phase: 0, delay: 0 }, 60, 120), makeNode("R1", "resistor", "Resistor 1", { resistance: 1000 }, 270, 120), makeNode("C1", "capacitor", "Capacitor 1", { capacitance: 0.000001, initialVoltage: 0 }, 480, 120), makeNode("GND1", "ground", "Ground 1", {}, 380, 280)], edges: [makeEdge("e1", "V1", "p", "R1", "p"), makeEdge("e2", "R1", "n", "C1", "p"), makeEdge("e3", "C1", "n", "GND1", "g"), makeEdge("e4", "V1", "n", "GND1", "g")] }) }),
  Object.freeze({ id: "parallel-resistors", label: "Parallel resistors", description: "Two resistor branches across a 10 V source.", simulationPreset: simulationPreset("dc_operating_point"), createGraph: () => ({ nodes: [makeNode("V1", "voltageSource", "Voltage Source 1", { waveform: "dc", voltage: 10 }, 60, 150), makeNode("R1", "resistor", "Resistor 1", { resistance: 1000 }, 360, 70), makeNode("R2", "resistor", "Resistor 2", { resistance: 2000 }, 360, 230), makeNode("GND1", "ground", "Ground 1", {}, 600, 150), { id: "J1", type: "junction", position: { x: 230, y: 150 }, data: { kind: "junction", portKind: "electrical" } }], edges: [makeEdge("e1", "V1", "p", "J1", "junction-left"), makeEdge("e2", "J1", "junction-right", "R1", "p"), makeEdge("e3", "J1", "junction-bottom", "R2", "p"), makeEdge("e4", "R1", "n", "GND1", "g"), makeEdge("e5", "R2", "n", "GND1", "g"), makeEdge("e6", "V1", "n", "GND1", "g")] }) }),
  Object.freeze({ id: "rl-transient", label: "RL transient", description: "10 V source driving a resistor-inductor transient response.", simulationPreset: simulationPreset("transient", { start: 0, stop: 0.00005, step: 0.0000001 }), createGraph: () => ({ nodes: [makeNode("V1", "voltageSource", "Voltage Source 1", { waveform: "dc", voltage: 10 }, 70, 140), makeNode("R1", "resistor", "Resistor 1", { resistance: 1000 }, 290, 140), makeNode("L1", "inductor", "Inductor 1", { inductance: 0.01, initialCurrent: 0 }, 500, 140), makeNode("GND1", "ground", "Ground 1", {}, 390, 300)], edges: [makeEdge("e1", "V1", "p", "R1", "p"), makeEdge("e2", "R1", "n", "L1", "p"), makeEdge("e3", "L1", "n", "GND1", "g"), makeEdge("e4", "V1", "n", "GND1", "g")] }) }),
  Object.freeze({ id: "rlc-transient", label: "RLC transient", description: "10 V source driving a resistor-inductor-capacitor transient response.", simulationPreset: simulationPreset("transient", { start: 0, stop: 0.005, step: 0.000005 }), createGraph: () => ({ nodes: [makeNode("V1", "voltageSource", "Voltage Source 1", { waveform: "dc", voltage: 10 }, 50, 140), makeNode("R1", "resistor", "Resistor 1", { resistance: 100 }, 240, 140), makeNode("L1", "inductor", "Inductor 1", { inductance: 0.01, initialCurrent: 0 }, 430, 140), makeNode("C1", "capacitor", "Capacitor 1", { capacitance: 0.000001, initialVoltage: 0 }, 620, 140), makeNode("GND1", "ground", "Ground 1", {}, 330, 300)], edges: [makeEdge("e1", "V1", "p", "R1", "p"), makeEdge("e2", "R1", "n", "L1", "p"), makeEdge("e3", "L1", "n", "C1", "p"), makeEdge("e4", "C1", "n", "GND1", "g"), makeEdge("e5", "V1", "n", "GND1", "g")] }) }),
  Object.freeze({ id: "diode-rectifier", label: "Diode rectifier", description: "5 V source, current-limiting resistor and silicon-style diode.", simulationPreset: simulationPreset("dc_operating_point"), createGraph: () => ({ nodes: [makeNode("V1", "voltageSource", "Voltage Source 1", { waveform: "dc", voltage: 5 }, 60, 140), makeNode("R1", "resistor", "Resistor 1", { resistance: 1000 }, 270, 140), makeNode("D1", "diode", "Diode 1", { forwardVoltage: 0.7, onResistance: 1 }, 480, 140), makeNode("GND1", "ground", "Ground 1", {}, 380, 280)], edges: [makeEdge("e1", "V1", "p", "R1", "p"), makeEdge("e2", "R1", "n", "D1", "p"), makeEdge("e3", "D1", "n", "GND1", "g"), makeEdge("e4", "V1", "n", "GND1", "g")] }) }),
  Object.freeze({ id: "npn-bias", label: "NPN transistor bias", description: "Two-supply NPN common-emitter bias in the forward-active region.", simulationPreset: simulationPreset("dc_operating_point"), createGraph: () => ({ nodes: [makeNode("VCC", "voltageSource", "VCC", { waveform: "dc", voltage: 12 }, 560, 70), makeNode("RC", "resistor", "Collector resistor", { resistance: 1000 }, 560, 180), makeNode("Q1", "npnTransistor", "NPN Transistor 1", { vbeOn: 0.7, vceSat: 0.2, beta: 100 }, 560, 310), makeNode("RB", "resistor", "Base resistor", { resistance: 10000 }, 300, 310), makeNode("VBB", "voltageSource", "VBB", { waveform: "dc", voltage: 1.7 }, 80, 310), makeNode("GND1", "ground", "Ground 1", {}, 560, 460)], edges: [makeEdge("e1", "VCC", "p", "RC", "p"), makeEdge("e2", "RC", "n", "Q1", "c"), makeEdge("e3", "VBB", "p", "RB", "p"), makeEdge("e4", "RB", "n", "Q1", "b"), makeEdge("e5", "Q1", "e", "GND1", "g"), makeEdge("e6", "VCC", "n", "GND1", "g"), makeEdge("e7", "VBB", "n", "GND1", "g")] }) }),
  Object.freeze({ id: "npn-low-side-switch", label: "NPN low-side switch", description: "A square-wave base drive switches a resistive load with an NPN transistor.", simulationPreset: simulationPreset("transient", { start: 0, stop: 0.002, step: 0.000001 }), createGraph: () => ({ nodes: [makeNode("VCC", "voltageSource", "VCC", { waveform: "dc", voltage: 12 }, 560, 70), makeNode("RLOAD", "resistor", "Load resistor", { resistance: 1000 }, 560, 190), makeNode("Q1", "npnTransistor", "NPN Transistor 1", { vbeOn: 0.7, vceSat: 0.2, beta: 100 }, 560, 340), makeNode("VIN", "voltageSource", "Gate drive", { waveform: "square", amplitude: 2.5, offset: 2.5, frequency: 1000, phase: 0, delay: 0 }, 80, 340), makeNode("RB", "resistor", "Base resistor", { resistance: 10000 }, 300, 340), makeNode("GND1", "ground", "Ground 1", {}, 560, 490)], edges: [makeEdge("e1", "VCC", "p", "RLOAD", "p"), makeEdge("e2", "RLOAD", "n", "Q1", "c"), makeEdge("e3", "VIN", "p", "RB", "p"), makeEdge("e4", "RB", "n", "Q1", "b"), makeEdge("e5", "Q1", "e", "GND1", "g"), makeEdge("e6", "VCC", "n", "GND1", "g"), makeEdge("e7", "VIN", "n", "GND1", "g")] }) }),
  Object.freeze({ id: "pnp-high-side-switch", label: "PNP high-side switch", description: "A square-wave base drive switches a resistive load from a 12 V supply with a PNP transistor.", simulationPreset: simulationPreset("transient", { start: 0, stop: 0.002, step: 0.000001 }), createGraph: () => ({ nodes: [makeNode("VCC", "voltageSource", "VCC", { waveform: "dc", voltage: 12 }, 560, 70), makeNode("Q1", "pnpTransistor", "PNP Transistor 1", { vbeOn: 0.7, vceSat: 0.2, beta: 100 }, 560, 250), makeNode("RLOAD", "resistor", "Load resistor", { resistance: 1000 }, 560, 390), makeNode("VIN", "voltageSource", "Gate drive", { waveform: "square", amplitude: 6, offset: 6, frequency: 1000, phase: 0, delay: 0 }, 80, 250), makeNode("RB", "resistor", "Base resistor", { resistance: 10000 }, 300, 250), makeNode("GND1", "ground", "Ground 1", {}, 560, 520)], edges: [makeEdge("e1", "VCC", "p", "Q1", "e"), makeEdge("e2", "Q1", "c", "RLOAD", "p"), makeEdge("e3", "RLOAD", "n", "GND1", "g"), makeEdge("e4", "VIN", "p", "RB", "p"), makeEdge("e5", "RB", "n", "Q1", "b"), makeEdge("e6", "VCC", "n", "GND1", "g"), makeEdge("e7", "VIN", "n", "GND1", "g")] }) }),
]);
